source 'https://github.com/CocoaPods/Specs.git'

target 'PLColors', :exclusive => true do
  pod "PLColors", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "PLColors", :path => "../"

  pod 'Kiwi'
end
